services:
  - type: web
    runtime: node
    name: curl-alan
    repo: https://github.com/ayushmittal-1/curl-alan.git
    branch: master
    buildCommand: "npm install"
    startCommand: node server.js
    plan: free
    envVars: []
